#!/bin/sh

case "$HOSTNAME" in
        "t1040rdb" | "T1040RDB" )
                DEF_CFG_PATH=/usr/etc/odp_test_config_t4.xml
                IF1=fm0-mac1
                IF2=fm0-mac2
                ;;
        "p4080ds" | "P4080DS" )
                DEF_CFG_PATH=/usr/etc/odp_test_config_p4.xml
                IF1=fm1-mac1
                IF2=fm1-mac2
                ;;
        * )
                echo "Platform $HOSTNAME not supported"
                exit 0
                ;;
esac

export DEF_CFG_PATH=$DEF_CFG_PATH
export DEF_PCD_PATH=/usr/etc/odp_pktio_pcd.xml

fmc -c $DEF_CFG_PATH -p $DEF_PCD_PATH -a

./odp_pktio -i $IF1,$IF2 -m 1&
