#! /bin/sh
echo "Update submodules"
git submodule update --init
cd platform/linux-dpaa2/flib/qbman/.
git am ../workaround_patches/0001-Removing-Compilation-error.patch
git am ../workaround_patches/0001-bugfix-in-qbman_swp_enqueue_multiple-API-for-multipl.patch
git am ../workaround_patches/0002-Enhancing-qbman_swp_enqueue_multiple-for-multi-DCAs.patch
cd -

set -x
aclocal -I config -I m4
libtoolize --copy
autoheader
automake --add-missing --copy --warnings=all
autoconf --force
