#!/bin/bash

# Copyright (c) 2015 Freescale Semiconductor, Inc.
# Copyright 2016 NXP
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#	notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#	notice, this list of conditions and the following disclaimer in the
#	documentation and/or other materials provided with the distribution.
#     * Neither the name of Freescale Semiconductor nor the
#	names of its contributors may be used to endorse or promote products
#	derived from this software without specific prior written permission.
#
#
# ALTERNATIVELY, this software may be distributed under the terms of the
# GNU General Public License ("GPL") as published by the Free Software
# Foundation, either version 2 of that License or (at your option) any
# later version.
#
# THIS SOFTWARE IS PROVIDED BY Freescale Semiconductor ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Freescale Semiconductor BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Bash-style exports, to be sourced from within the "usdpaa" tree
# when developing and building locally (rather than via Poky).
#
# Note, it hard-codes a toolchain path to that currently installed
# by Poky (so adjust as required).
#
# Note also, it hard-codes include and lib paths to the rootfs
# staging area managed by Poky, assuming that this usdpaa tree
# is a sibling of the Poky tree (again, adjust as required).

board2soc()
{
       case $1 in
               [pP]1023*) echo p1023;;
               [pP]2041*) echo p2041;;
               [pP]3041*) echo p3041;;
               [pP]4080*) echo p4080;;
               [pP]5020*) echo p5020;;
               [pP]5040*) echo p5040;;
               [bB]4860*) echo b4860;;
               [tT]4240*) echo t4240;;
               [tT]1040*) echo t1040;;
               [tT]2080*) echo t2080;;
               [tT]1023*) echo t1023;;
               [tT]1024*) echo t1024;;
               [lL][sS]1043*) echo ls1043;;
       esac
}

board2cpu()
{
       case $1 in
               [lL][sS]1043*-be) echo aarch64_be;;
               [lL][sS]1043*) echo aarch64;;
               *) echo -n "powerpc";;
       esac
}

soc2arch()
{
       case $1 in
               [lL][sS]1043*) echo arm64;;
               *) echo -n "powerpc";;
       esac
}

soc2cc()
{
       case $1 in
               [lL][sS]1043*-be) echo aarch64_be;;
               [lL][sS]1043*) echo aarch64;;
               *) echo -n "powerpc";;
       esac
}

soc2cflags()
{
        case $1 in
                [lL][sS]1043*-[bB][eE]) echo -n "-mbig-endian";;
                *) echo -n "";;
        esac
}

declare -l board=p4080ds
declare -i OLD_OPTIND=$OPTIND
while getopts "m:" flags
do

	case $flags in
		m)
			case $OPTARG in
				p1023ds | p2041rdb | p3041ds | p4080ds | p5020ds | p5020ds-64b | p5040ds | p5040ds-64b | b4860qds | b4860qds-64b | t4240qds | t4240qds-64b | t4240rdb | t4240rdb-64b | t1040qds | t1040qds-64b | t1040rdb | t1040rdb-64b | t2080qds | t2080qds-64b | t1023rdb | t1023rdb-64b | t1024rdb | t1024rdb-64b | t1024qds | t1024qds-64b | ls1043ardb | ls1043ardb-be | ls1043a-simu | ls1043aqds | ls1043aqds-be)
					board=$OPTARG
					;;
				*)
					echo Unknown board $OPTARG. Defaulting to $board
					;;
			esac
			;;
		?) echo Defaulting to $board;;
	esac
done
OPTIND=$OLD_OPTIND
declare -x -u SOC=$(board2soc $board)

if [[ $board =~ "-64b" ]]
then
	prefix="64"
else
	prefix=""
fi

export ARCH=$(soc2arch $board)${prefix}
export CC="${CROSS_COMPILE}gcc"
export LD="${CROSS_COMPILE}ld"
export EXTRA_CFLAGS=$(soc2cflags $board)
unset -v OLD_OPTIND board prefix
